{% set version = '0.2.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-geoarrow
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geoarrow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geoarrow/geoarrow_{{ version }}.tar.gz
  sha256: 44d4bb29be6aa3e05320151eb6efd0df7ff498d3298ff4e9a94480b449a7bc69

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib('c') }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-nanoarrow >=0.5.0
    - r-wk >=0.9.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-nanoarrow >=0.5.0
    - r-wk >=0.9.0

test:
  commands:
    - $R -e "library('geoarrow')"           # [not win]
    - "\"%R%\" -e \"library('geoarrow')\""  # [win]

about:
  home: https://github.com/geoarrow/geoarrow-r
  license: Apache-2.0
  summary: Provides extension types and conversions to between R-native object types and 'Arrow'
    columnar types. This includes integration among the 'arrow', 'nanoarrow', 'sf',
    and 'wk' packages such that spatial metadata is preserved wherever possible. Extension
    type implementations ensure first-class geometry data type support in the 'arrow'
    and 'nanoarrow' packages.
  license_family: APACHE
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/r
    - tdsmith

# Package: geoarrow
# Title: Extension Types for Spatial Data for Use with 'Arrow'
# Version: 0.2.1
# Authors@R: c( person(given = "Dewey", family = "Dunnington", role = c("aut", "cre"), email = "dewey@dunnington.ca", comment = c(ORCID = "0000-0002-9415-4582")), person(given = "Anthony", family = "North", email = "anthony.jl.north@gmail.com", role = c("ctb")), person("Apache Software Foundation", email = "dev@arrow.apache.org", role = c("cph")), person("Ulf", "Adams", role = "cph"), person("Daniel", "Lemire", role = "cph"), person("Joao Paulo", "Magalhaes", role = "cph") )
# Description: Provides extension types and conversions to between R-native object types and 'Arrow' columnar types. This includes integration among the 'arrow', 'nanoarrow', 'sf', and 'wk' packages such that spatial metadata is preserved wherever possible. Extension type implementations ensure first-class geometry data type support in the 'arrow' and 'nanoarrow' packages.
# License: Apache License (>= 2)
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Imports: nanoarrow (>= 0.5.0), wk (>= 0.9.0)
# LinkingTo: wk
# Config/testthat/edition: 3
# URL: https://github.com/geoarrow/geoarrow-r
# BugReports: https://github.com/geoarrow/geoarrow-r/issues
# Depends: R (>= 3.6.0)
# Suggests: arrow, R6, sf, testthat (>= 3.0.0)
# NeedsCompilation: yes
# Packaged: 2024-06-12 18:49:48 UTC; deweydunnington
# Author: Dewey Dunnington [aut, cre] (<https://orcid.org/0000-0002-9415-4582>), Anthony North [ctb], Apache Software Foundation [cph], Ulf Adams [cph], Daniel Lemire [cph], Joao Paulo Magalhaes [cph]
# Maintainer: Dewey Dunnington <dewey@dunnington.ca>
# Repository: CRAN
# Date/Publication: 2024-06-13 06:50:02 UTC
