{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-geoarrow
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/geoarrow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/geoarrow/geoarrow_{{ version }}.tar.gz
  sha256: 1fb3295bd318fd323ae5392de7e552e004a8d2c165752054663d6f37881c416b

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-nanoarrow >=0.5.0          # [build_platform != target_platform]
    - r-wk >=0.9.0                 # [build_platform != target_platform]
  host:
    - r-base
    - r-nanoarrow >=0.5.0
    - r-wk >=0.9.0
  run:
    - r-base
    - r-nanoarrow >=0.5.0
    - r-wk >=0.9.0

test:
  commands:
    - $R -e "library('geoarrow')"           # [not win]
    - "\"%R%\" -e \"library('geoarrow')\""  # [win]

about:
  home: https://github.com/geoarrow/geoarrow-r
  license: Apache-2.0
  summary: Provides extension types and conversions to between R-native object types and 'Arrow' columnar types. This includes integration among the 'arrow', 'nanoarrow', 'sf', and 'wk' packages such that spatial metadata is preserved wherever possible. Extension type implementations ensure first-class geometry data type
    support in the 'arrow' and 'nanoarrow' packages.
  license_family: APACHE
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - conda-forge/r
    - tdsmith
